# This is Dockerfile for development purposes only
# So it run npm run start rather than npm run build
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]